webdav:
    port: 8080
    user: acarreon
    password: Tricounty1
api:
    prefix: /api
auth:
    login_required: true
database:
    path: /config/altmount.db
metadata:
    root_path: /config/metadata
    delete_source_nzb_on_removal: false
streaming:
    max_download_workers: 15
    max_cache_size_mb: 32
health:
    enabled: false
    library_dir: null
    cleanup_orphaned_metadata: false
    check_interval_seconds: 5
    max_connections_for_health_checks: 5
    segment_sample_percentage: 5
    library_sync_interval_minutes: 360
    library_sync_concurrency: 0
rclone:
    path: /config
    password: ""
    salt: ""
    rc_enabled: true
    rc_url: ""
    rc_port: 5573
    rc_user: admin
    rc_pass: admin
    rc_options: {}
    mount_enabled: true
    mount_options: {}
    log_level: DEBUG
    uid: 1001
    gid: 1001
    umask: "002"
    buffer_size: 32M
    attr_timeout: 1s
    transfers: 4
    cache_dir: /config/cache
    vfs_cache_mode: full
    vfs_cache_poll_interval: ""
    vfs_read_chunk_size: ""
    vfs_cache_max_size: 50G
    vfs_cache_max_age: 504h
    read_chunk_size: 32M
    read_chunk_size_limit: 2G
    vfs_read_ahead: 128M
    dir_cache_time: 10m
    vfs_cache_min_free_space: 1G
    vfs_disk_space_total: 1G
    vfs_read_chunk_streams: 4
    allow_other: true
    allow_non_empty: true
    read_only: false
    timeout: 10m
    syslog: true
    no_mod_time: false
    no_checksum: false
    async_read: true
    vfs_fast_fingerprint: false
    use_mmap: false
import:
    max_processor_workers: 2
    queue_processing_interval_seconds: 5
    allowed_file_extensions:
        - .mp4
        - .mkv
        - .avi
        - .mov
        - .wmv
        - .flv
        - .webm
        - .m4v
        - .mpg
        - .mpeg
        - .m2ts
        - .ts
        - .vob
        - .3gp
        - .3g2
        - .h264
        - .h265
        - .hevc
        - .ogv
        - .ogm
        - .strm
        - .iso
        - .img
        - .divx
        - .xvid
        - .rm
        - .rmvb
        - .asf
        - .asx
        - .wtv
        - .mk3d
        - .dvr-ms
    max_import_connections: 5
    import_cache_size_mb: 64
    segment_sample_percentage: 1
    import_strategy: NONE
    import_dir: null
log:
    file: /config/altmount.log
    level: info
    max_size: 100
    max_age: 30
    max_backups: 10
    compress: true
sabnzbd:
    enabled: true
    complete_dir: /complete
    categories: []
    fallback_host: ""
    fallback_api_key: ""
arrs:
    enabled: false
    max_workers: 5
    radarr_instances: []
    sonarr_instances: []
providers:
    - id: provider_1
      host: secure.news.easynews.com
      port: 563
      username: qbisftweeo
      password: szxr-txfi-owti
      max_connections: 12
      tls: true
      insecure_tls: false
      enabled: true
      is_backup_provider: false
mount_path: /config/altmount
profiler_enabled: false
